# Conda environment

name: viscoin

channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults

dependencies:
  - python=3.12

  # Deep learning libraries
  - pytorch>=2.5.0
  - torchvision>=0.20.0
  - pillow
  - tqdm
  - numpy

  # Development dependencies
  - pyright>=1.1.382
  - isort>=5.13.2
