name: Lint and Type Check

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache conda
        uses: actions/cache@v3
        env:
          # Increase this value to reset cache if etc/example-environment.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
            hashFiles('etc/example-environment.yml') }}

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: conda.yml
          activate-environment: viscoin
          use-only-tar-bz2: true # for caching

      - name: Install Pyright and Isort
        run: pip install pyright isort

      - name: Run Pyright
        run: pyright

      - name: Run isort
        run: isort . --check-only --diff
